var colleges = [
    {
      rank:1,
      name: "IIT Madras - Indian Institute of Technology - [IITM]",
      logo:"https://doe.iitm.ac.in/wp-content/uploads/2021/06/245-2451831_iit-madras-logo.png",
      location: "Chennai, Tamil Nadu",
      approvedBy: "AICTE",
      course: "B.Tech Computer Science Engineering",
      cutoff: 144,
      fees: 209550,
      averagePackage: 21480000,
      highestPackage: 198000000,
      userRating: 8.6,
      featured: true,
      reviews: 289,
      socialLife: "Best in Social Life",
      ranking: "#2nd/131 in India",
      basedOnUser:271
    },{
      rank:2,
      name: "IIT Delhi - Indian Institute of Technology - [IITD]",
      logo:"https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg/220px-Indian_Institute_of_Technology_Delhi_Logo.svg.png",
      location: "New Delhi, Delhi NCR",
      approvedBy: "AICTE",
      course: "B.Tech Computer Science Engineering",
      cutoff: 140,
      fees: 209550,
      averagePackage: 22480000,
      highestPackage: 198000000,
      userRating: 8.7,
      featured: true,
      reviews: 299,
      socialLife: "Best in Social Life",
      ranking: "#3rd/131 in India",
      basedOnUser:261
    },
  {
    rank:3,  
    name: "IIT Indore - Indian Institute of Technology - [IITI]",
    logo:"https://upload.wikimedia.org/wikipedia/en/c/c4/Indian_Institute_of_Technology%2C_Indore_Logo.png",
      location: "Indore, Madhya Pradesh",
      approvedBy: "AICTE",
      course: "B.Tech Computer Science Engineering",
      cutoff: 134,
      fees: 209550,
      averagePackage: 23480000,
      highestPackage: 198000000,
      userRating: 8.4,
      featured: true,
      reviews: 279,
      socialLife: "Best in Infrastructure",
      ranking: "#8th/131 in India",
      basedOnUser:251
    },{
      rank:4,
      name: "Parul University",
      logo:"https://i.pinimg.com/originals/35/4e/41/354e41b970004cac05cbe77bbc681ad8.png",
      location: "Vadodra, Gujarat",
      approvedBy: "AICTE, GNC Approved",
      course: "B.Tech Computer Science Engineering",
      cutoff: 174,
      fees: 219550,
      averagePackage: 23480000,
      highestPackage: 178000000,
      userRating: 8.1,
      featured: false,
      reviews: 219,
      socialLife: "Best in Social Life",
      ranking: "#10th/131 in India",
      basedOnUser:241
    },{
      rank:5,
      name: "IIT Bombay - Indian Institute of Technology - [IITB]",
      logo:"https://upload.wikimedia.org/wikipedia/sa/d/da/IIT_Bombay_logo.png",
      location: "Mumbai, Maharashtra",
      approvedBy: "AICTE, UGC Approved",
      course: "B.Tech Computer Science Engineering",
      cutoff: 134,
      fees: 269550,
      averagePackage: 20080000,
      highestPackage: 100000000,
      userRating: 8.3,
      featured: false,
      reviews: 269,
      socialLife: "Best in Infrastructure",
      ranking: "#1st/131 in India",
      basedOnUser:241
    },{
      rank:6,
      name: "Subharti University",
      logo:"https://upload.wikimedia.org/wikipedia/en/3/3d/SVSU-transparent-Logo.png",
      location: "Meerut, UttarPradesh",
      approvedBy: "AICTE",
      course: "B.Tech Computer Science Engineering",
      cutoff: 100,
      fees: 109550,
      averagePackage: 480000,
      highestPackage: 8000000,
      userRating: 7.6,
      featured: true,
      reviews: 219,
      socialLife: "Best in Social Life",
      ranking: "#23rd/131 in India",
      basedOnUser:231
    },{
      rank:7,
      name: "LNCT Indore",
      logo:"https://www.lnctindore.edu.in/wp-content/uploads/2021/08/LNCT-IND-1.png",
      location: "indore, Madhya Pradesh",
      approvedBy: "UGC Approved",
      course: "B.Tech Computer Science Engineering",
      cutoff: 104,
      fees: 109550,
      averagePackage: 450000,
      highestPackage: 6000000,
      userRating: 8.1,
      featured: true,
      reviews: 209,
      socialLife: "Best in Social Life",
      ranking: "#20th/131 in India",
      basedOnUser:231
    },{
      rank:8,
      name: "NIET",
      logo:"https://www.static-contents.youth4work.com/university/Documents/Colleges/collegeLogo/20221223142746.png?v=20221223142746",
      location: "Noida, Delhi NCR",
      approvedBy: "AKTU",
      course: "B.Tech Computer Science Engineering",
      cutoff: 124,
      fees: 106550,
      averagePackage: 380000,
      highestPackage: 4400000,
      userRating: 7.6,
      featured: true,
      reviews: 189,
      socialLife: "Best in Social Life",
      ranking: "#33rd/131 in India",
      basedOnUser:221
    },{
      rank:9,
      name: "IIT Roorkee - Indian Institute of Technology - [IITR]",
      logo:"https://upload.wikimedia.org/wikipedia/en/6/6f/Indian_Institute_of_Technology_Roorkee_logo.png",
      location: "Roorkee, Uttarakhand",
      approvedBy: "AICTE",
      course: "B.Tech Computer Science Engineering",
      cutoff: 144,
      fees: 209550,
      averagePackage: 21480000,
      highestPackage: 198000000,
      userRating: 8.6,
      featured: true,
      reviews: 289,
      socialLife: "Best in Social Life",
      ranking: "#3rd/131 in India",
       basedOnUser:211
    },{
      rank:10,
      name: "MIET",
      logo:"https://mietjmu.in/images/MIET.png",
      location: "Meerut, UttarPradesh",
      approvedBy: "AKTU",
      course: "B.Tech Computer Science Engineering",
      cutoff: 124,
      fees: 129550,
      averagePackage: 320000,
      highestPackage: 600000,
      userRating: 7.1,
      featured: true,
      reviews: 156,
      socialLife: "Best in Social Life",
      ranking: "#44th/131 in India",
      basedOnUser:201
    }
  ]

export default colleges;